# Generated by Django 6.0.4 on 2026-06-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoria_mascota_producto_turno_usuario_vacuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
