# Generated by Django 6.0.3 on 2026-06-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('api', '0005_categorias_iniciales')]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
