# Generated by Django 6.0.3 on 2026-06-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_categorias_iniciales'),
        ('api', '0007_remove_usuario_rol_usuario_role_usuario_token_and_more'),
    ]

    operations = [
    ]
