# Generated by Django 6.0.3 on 2026-06-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20260607_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='id_vacuna',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='nombre_vacuna',
            field=models.CharField(default='sin datos', max_length=100),
            preserve_default=False,
        ),
    ]
